# Generated by Django 5.0.2 on 2024-02-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_system_app', '0002_product_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('have_access', 'Есть доступ к продукту'),)},
        ),
    ]
