# Generated by Django 5.0.2 on 2024-02-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training_system_app', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
