# Generated by Django 5.0.2 on 2024-02-29 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_system_app', '0005_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='group',
            name='min_users',
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(default=None, related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='max_users',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='min_users',
            field=models.IntegerField(default=5),
        ),
    ]
