# Generated by Django 5.0.2 on 2024-03-01 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_system_app', '0009_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(default=None, null=True, related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
